// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type User struct {
	ID        int32
	Username  string
	Password  string
	Firstname sql.NullString
	Lastname  sql.NullString
}
